name: Checking action

on: push

jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Action
        id: run-action
        uses: ./.github/actions/composite-action
        with:
          greet: "Ayesha Azad"

      - name: Check Output
        run: echo "${{steps.run-action.outputs.greeting}}"
