name: Check Secret Length

on: push

jobs:
  check-secret-length:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Secret Length
        id: output
        uses: ./.github/actions/secrets-length
        with:
          secret: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Check Output
        run: echo "The output is ${{steps.output.outputs.length}}."
