name: Checking action

on: push

jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action
        uses: ./.github/actions/composite-action/action.yaml
        with:
          greet: "Ayesha Azad"
