name: Check file

on: push

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checking if a file exists 
        id: exist-id
        uses: ./.github/actions/does-file-exist
        with:
          file: index.js

      - name: Get Output 
        run: |
          if [[ ${{ steps.exist-id.outputs.exists }} == "true" ]]
          then
            echo "The file exists."
          else 
            echo "The file does not exist."
          fi 
          
