name: Check Matrix Composite Action

on: push

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["frontend", "backend"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Matrix
        uses: ./.github/actions/matrix-composite
        with:
          data: ${{matrix.folder}}
