name: Checking Action 

on: push 

jobs:
  random-square-gen:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Testing Action
        id: random-num-id
        uses: ./.github/actions/another-composite-action
        with:
          number: "2"

      - name: Checking Output
        run: echo ${{ steps.random-num-id.outputs.random-number }}
