name: Hello World

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from Ayesha Azad from ${{github.repository}} at ${{github.ref_name}} by ${{github.actor}}"

  goodbye-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Goodbye
        run: echo "Goodbye from Ayesha Azad from ${{github.repository}} at ${{github.ref_name}} by ${{github.actor}}"
