name: Job Dependency 

on: push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Job
        run: echo "This is a build job."
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Job
        run: echo "This is a test job."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build Job
        run: echo "This is a deploy job."
