name: Multi Step Workflow 

on: push 

jobs:
  multi-step-test:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: |
          date 
          echo "-------------"
          ls -la
          echo "-------------"
          hostnamectl
