name: Secrets and Environment Variables

on: push

jobs:
  secrets-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
      - name: Print Environment
        run: echo "The environment variable is ${{ vars.MY_VAR }}"
